import { type NextPage } from "next";
import Head from "next/head";
import { Flex, Text } from "@chakra-ui/react";
import TaskTabs from "../components/home/taskTabs";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Planning Poker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text>Here's your recent work</Text>
      <Flex
        direction={["column", "column", "row"]}
        width="100%"
        justifyContent="center"
        gap={32}
        paddingTop={8}
      >
        <TaskTabs />
      </Flex>
    </>
  );
};

export default Home;
