import { type NextPage } from "next";
import Head from "next/head";
import { Suspense } from "react";
import { Text } from "@chakra-ui/react";
import StoryTabs from "../components/home/storyTabs";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback={<Text>Loading</Text>}>
        <StoryTabs />
      </Suspense>
    </>
  );
};

export default Home;
